version: '3'

volumes:
  blenderDb:

services:
  pod:
    image: centrifugeio/pod:centapi-improve-logging-2023090616-a9c22319

  blender-db:
    image: mongo
    volumes:
      - blenderDb:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${BLENDER_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${BLENDER_DB_PASS}
      MONGO_INITDB_DATABASE: blender

  blender-influx:
    image: ghcr.io/embrio-tech/centrifuge-influx:main
    ports: []
    #  - 9229:9229
    depends_on:
      - blender-db
    environment:
      DB_URI: 'mongodb://${BLENDER_DB_USER}:${BLENDER_DB_PASS}@blender-db:27017/blender?authSource=admin'
      POOL_ID: ${POOL_ID}
      PROXY_KEYRING_URI: ${PROXY_KEYRING_URI}
      OPERATOR_ADDRESS: ${OPERATOR_ADDRESS}

  blender-outflux:
    image: ghcr.io/embrio-tech/centrifuge-outflux:main
    ports:
      - 5010:5000
      - 9229:9229
    depends_on:
      - blender-db
    environment:
      DB_URI: 'mongodb://${BLENDER_DB_USER}:${BLENDER_DB_PASS}@blender-db:27017/blender?authSource=admin'
      LOGGER_LEVEL: debug
      API_KEY: ${BLENDER_API_SECRET}
